[env:esp32]
platform = espressif32
framework = arduino
board = esp32doit-devkit-v1
monitor_speed = 115200
board_build.partitions = partitions.csv
build_flags =
            -D SOC_WIFI_SUPPORTED=1
            -D CORE_DEBUG_LEVEL=3
lib_deps = 
            https://github.com/vshymanskyy/StreamDebugger
            https://github.com/vshymanskyy/TinyGSM
            rc-switch

upload_protocol = espota
upload_port = alarm-hub-esp32.local