[env:esp32-s3-wroom-1-n8r8]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1
monitor_speed = 115200

board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.partitions = partitions.csv
board_build.extra_flags = 
            -D BOARD_HAS_PSRAM
build_flags =
            -D SOC_WIFI_SUPPORTED=1
            -D CORE_DEBUG_LEVEL=3
            -D ARDUINO_USB_CDC_ON_BOOT=0
            -D FASTLED_RMT5=0
lib_deps = 
            https://github.com/vshymanskyy/StreamDebugger
            https://github.com/vshymanskyy/TinyGSM
            rc-switch
            ; https://github.com/me-no-dev/ESPAsyncWebServer
            ; https://github.com/me-no-dev/AsyncTCP

           
            

            ; Create and add following independant libraries
            ; mqtt
            ; http
            ; ntp
            ; ota
            ; cypto
            ; ble

            ; Create following local libraries
            ; db, setCustom(JsonDocument &doc), getCustom(JsonDocument &doc)
            ; vigil will handle all the logic & free main() only project specific tasks